import { useEffect, useState } from 'react'
import { catalogPerformanceRepo, clientesRepo, ejecutivosRepo } from './data/repositories.js'
import { getCatalogAccess } from './data/catalogLink.js'

const money=v=>Number(v||0).toLocaleString('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0})
const pct=v=>v==null?'—':`${(Number(v)*100).toFixed(1)}%`
const label=v=>v==null||v===''?'—':String(v)

function Client360({cliente,clienteKey,onClose}){const [catalogAccess,setCatalogAccess]=useState({active:false,url:null});const [executives,setExecutives]=useState([]);const [selected,setSelected]=useState('');const [saving,setSaving]=useState(false);useEffect(()=>{if(!clienteKey)return;Promise.allSettled([getCatalogAccess(clienteKey),ejecutivosRepo.listar()]).then(([a,e])=>{if(a.status==='fulfilled')setCatalogAccess(a.value||{});if(e.status==='fulfilled')setExecutives(e.value||[])})},[clienteKey]);const assign=async()=>{if(!selected||!clienteKey)return;setSaving(true);try{await clientesRepo.asignar(clienteKey,selected);onClose();window.location.reload()}catch(_){setSaving(false)}};return <div className="cc-modal" role="dialog" aria-modal="true"><div className="cc-modal-card"><button className="cc-close" onClick={onClose}>×</button><span className="cc-subtitle">CLIENTE 360</span><h2>{label(cliente.nombre||cliente.razon_social)}</h2><div className="cc-detail-grid"><div><span>VENTA MTD</span><b>{money(cliente.venta_mtd??cliente.ventaMtd)}</b></div><div><span>VARIACIÓN</span><b>{pct(cliente.variacion??cliente.variacion_mtd)}</b></div><div><span>RIESGO</span><b>{label(cliente.riesgo)}</b></div><div><span>SIN COMPRA</span><b>{Number(cliente.dias_sin_comprar??cliente.diasSinComprar??0)} días</b></div><div><span>EJECUTIVO</span><b>{label(cliente.ejecutivo||cliente.ejecutivo_nombre)}</b></div><div><span>ZONA</span><b>{label(cliente.zona)}</b></div></div><div className="cc-catalog-status"><span>CATÁLOGO B2B</span><strong>{catalogAccess.active?'● ACTIVO':'○ NO PUBLICADO'}</strong>{catalogAccess.url&&<button onClick={()=>window.open(catalogAccess.url,'_blank','noopener,noreferrer')}>Abrir catálogo</button>}</div><div className="cc-admin-action"><h3>Acción gerencial</h3><label>Asignar ejecutivo</label><select value={selected} onChange={e=>setSelected(e.target.value)} disabled={saving}><option value="">Seleccionar…</option>{executives.map(e=><option key={e.id} value={e.id}>{e.nombre} · {label(e.zona)}</option>)}</select><button onClick={assign} disabled={saving||!selected}>{saving?'Guardando…':'Confirmar asignación'}</button></div></div></div>}

function B2BPerformance({data,loading,onRefresh}){return <section className="cc-b2b-performance"><div className="cc-section-head"><div><span className="cc-subtitle">CANAL B2B</span><h2>Performance del catálogo</h2></div><button onClick={onRefresh} disabled={loading}>{loading?'Actualizando…':'Actualizar'}</button></div><div className="cc-kpis"><div><span>CATÁLOGOS ACTIVOS</span><b>{data?data.activeCatalogs.toLocaleString('es-CL'):'—'}</b></div><div><span>PEDIDOS</span><b>{data?data.orders.toLocaleString('es-CL'):'—'}</b></div><div><span>CLIENTES COMPRADORES</span><b>{data?data.orderingClients.toLocaleString('es-CL'):'—'}</b></div><div><span>VENTA</span><b>{data?money(data.sales):'—'}</b></div><div><span>TICKET PROMEDIO</span><b>{data?money(data.avgTicket):'—'}</b></div><div><span>RECOMPRA</span><b>{data?pct(data.repurchaseRate):'—'}</b></div><div><span>RECUPERADOS</span><b>{data?data.recoveredClients.toLocaleString('es-CL'):'—'}</b></div></div></section>}

function RiskQueue({rows,loading,onRefresh,onOpen}){return <section className="cc-risk-queue"><div className="cc-section-head"><div><span className="cc-subtitle">ACCIÓN GERENCIAL</span><h2>Clientes en riesgo</h2><p>Prioridad comercial basada en riesgo, días sin compra y caída de venta.</p></div><button onClick={onRefresh} disabled={loading}>{loading?'Actualizando…':'Actualizar'}</button></div>{rows.length?<div className="cc-risk-table"><div className="cc-risk-head"><span>CLIENTE</span><span>EJECUTIVO</span><span>RIESGO</span><span>SIN COMPRA</span><span>VENTA MTD</span><span>VARIACIÓN</span><span>ACCIÓN</span></div>{rows.map((c,i)=><div className="cc-risk-row" key={c.id||c.cliente_key||i}><span><b>{label(c.nombre||c.razon_social)}</b><small>{label(c.cliente_key||c.rut)}</small></span><span>{label(c.ejecutivo||c.ejecutivo_nombre)}</span><span>{label(c.riesgo)}</span><span>{Number(c.dias_sin_comprar??c.diasSinComprar??0).toLocaleString('es-CL')} días</span><span>{money(c.venta_mtd??c.ventaMtd)}</span><span>{pct(c.variacion??c.variacion_mtd)}</span><button onClick={()=>onOpen(c)}>Ver 360°</button></div>)}</div>:<div className="cc-empty">No hay clientes que cumplan los criterios actuales de riesgo.</div>}</section>}

export default function ControlCenter(){const [performance,setPerformance]=useState(null);const [risks,setRisks]=useState([]);const [selectedClient,setSelectedClient]=useState(null);const [loading,setLoading]=useState(true);const load=async()=>{setLoading(true);try{const [p,r]=await Promise.all([catalogPerformanceRepo.resumen(),catalogPerformanceRepo.riskQueue()]);setPerformance(p);setRisks(r)}finally{setLoading(false)}};useEffect(()=>{load()},[]);return <main className="control-center"><B2BPerformance data={performance} loading={loading} onRefresh={load}/><RiskQueue rows={risks} loading={loading} onRefresh={load} onOpen={setSelectedClient}/>{selectedClient&&<Client360 cliente={selectedClient} clienteKey={selectedClient.cliente_key||selectedClient.id} onClose={()=>setSelectedClient(null)}/>}</main>}
